-- ============================================================
-- Seed: 2026-2027 Trail Life MN-9871 Leadership signups
--
-- Generated by app/scripts/build-seed.mjs from the legacy
-- static HTML pages under signup-static/. Run again to refresh.
-- 
-- Run via Supabase Studio SQL Editor, or:
--   psql "$DATABASE_URL" -f app/supabase/seed.sql
-- ============================================================

begin;

-- Adults event ---------------------------------------------
insert into public.events (slug, title, subtitle, season, is_published, theme)
values (
  'leadership-adults-2026-27',
  'Adult Volunteer Roles · 2026–2027',
  'Step up and serve. Trail Life MN-9871 leadership signup for dads and adults.',
  '2026-2027',
  true,
  'trail-life-green'
)
on conflict (slug) do update set
  title       = excluded.title,
  subtitle    = excluded.subtitle,
  season      = excluded.season,
  is_published= excluded.is_published,
  theme       = excluded.theme;

do $$
declare
  adults_id uuid;
  youth_id  uuid;
begin
  select id into adults_id from public.events where slug = 'leadership-adults-2026-27';
  delete from public.slots where event_id = adults_id;

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    0,
    'Committee',
    'Troopmaster',
    'Senior leader of Troop MN-9871. Filled by Nick Stromwall.',
    'The Troopmaster holds final responsibility for the troop program, culture, and mission. He casts vision, develops leaders, resolves conflict, and ensures the troop is faithfully pursuing its mission to raise Christ-centered young men.',
    1,
    true,
    '1 Peter 5:2 — Shepherd the flock of God that is among you.',
    'Full season commitment',
    'Troop Committee Chair',
    '["Troop program runs with clarity and purpose all year","Leaders are developed and empowered to serve","Boys are known, challenged, and growing in faith","The troop is healthy and expanding"]'::jsonb,
    '["Not doing everything himself — he leads leaders","Not above accountability — serves under the Committee Chair"]'::jsonb,
    '["Nick Stromwall"]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    1,
    'Committee',
    'Assistant Troopmaster',
    'Training to lead. Three men stepping into Troopmaster capacity.',
    'The Assistant Troopmaster role exists to build leadership depth. Three men are being invited into this role to train alongside Nick and develop the judgment, relationships, and operational knowledge to lead the troop. This is a succession and development role — high trust, high investment.',
    3,
    true,
    '2 Timothy 2:2 — Entrust to faithful men who will teach others also.',
    '6–10 hours per month',
    'Troopmaster',
    '["Deeply familiar with every aspect of troop operations by December","Building genuine relationships with leaders, boys, and families","Ready to step into full Troopmaster responsibilities when called upon","Growing in confidence and competence as a troop leader"]'::jsonb,
    '["Not a ceremonial title — this is active mentoring and learning","Not expected to have all the answers yet — that is what the training is for"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    2,
    'Committee',
    'Committee Chair',
    'Leads the troop committee and governs with wisdom and accountability.',
    'The Committee Chair leads the troop''s core committee — the governing body that provides oversight, accountability, and strategic direction for Troop MN-9871. He runs monthly committee meetings, holds the Troopmaster accountable, manages conflict resolution, and ensures the troop is aligned with its covenant mission and church partnership.',
    1,
    true,
    'Proverbs 11:14 — In an abundance of counselors there is safety.',
    '3–5 hours per month',
    'Church Ministry Leadership',
    '["Core committee meets monthly with clear agenda and follow-through","Troopmaster has a trusted partner for governance decisions","Financial and operational accountability maintained throughout the year","Troop leadership culture reflects biblical servant leadership"]'::jsonb,
    '["Not the day-to-day program leader — that is the Troopmaster","Not above the Troopmaster relationally — a peer who provides accountability"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    3,
    'Committee',
    'Chaplain',
    'Spiritual shepherd for leaders, boys, and families.',
    'The Chaplain provides spiritual oversight for Troop MN-9871 — praying for leaders and families, leading devotionals at committee meetings, and ensuring the troop''s spiritual health is tended to with intentionality. He is also the primary point of care when a leader or family is going through a difficult season.',
    1,
    true,
    'Colossians 3:16 — Let the word of Christ dwell in you richly.',
    '3–5 hours per month',
    'Troopmaster / Committee Chair',
    '["Leaders and families feel spiritually supported throughout the year","Committee meetings open with meaningful prayer and Scripture","Troop culture is visibly Christ-centered, not just programmatically","Boys are pointed toward Christ through the chaplain''s presence"]'::jsonb,
    '["Not responsible for all spiritual content in meetings — that is shared across leadership","Not a pastor to the whole church — shepherds within the troop context"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    4,
    'Committee',
    'Asst. Chaplain — Woodlands',
    'Spiritual care and devotional support for K–5th grade boys.',
    'The Assistant Chaplain for Woodlands assists the Chaplain in providing spiritual oversight for the K through 5th grade program. This includes leading or supporting devotional moments at Woodlands meetings, praying for families, and helping Trail Guides integrate faith meaningfully into badge work and patrol culture.',
    1,
    false,
    'Mark 10:14 — Let the children come to me; do not hinder them.',
    '2–3 hours per month',
    'Chaplain',
    '["Woodlands boys encounter Scripture and prayer regularly at Thursday meetings","Trail Guides feel supported in their spiritual leadership of boys","Families of Woodlands boys feel the troop is genuinely faith-centered","Devotional content is age-appropriate and engaging for younger boys"]'::jsonb,
    '["Not teaching full lessons — that is the Trail Guide''s role","Not responsible for discipling every boy individually — partners with guides"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    5,
    'Committee',
    'Asst. Chaplain — NAV/ADS',
    'Spiritual care and discipleship for middle and high school boys.',
    'The Assistant Chaplain for Navigators and Adventurers assists the Chaplain in serving the spiritual needs of middle and high school boys. This includes supporting devotional moments, walking alongside older boys through faith questions, and helping Trail Guides disciple teenage Trailmen with depth and intentionality.',
    1,
    false,
    'Psalm 119:9 — How can a young man keep his way pure? By guarding it according to your word.',
    '2–3 hours per month',
    'Chaplain',
    '["NAV/ADS boys encounter real, substantive spiritual content — not just moral advice","Older boys feel safe asking hard faith questions with trusted leaders","Trail Guides for NAV/ADS have a chaplain partner they can call on","Devotional moments are honest, age-appropriate, and rooted in Scripture"]'::jsonb,
    '["Not expected to have every theological answer — points boys to Scripture and trusted resources","Not the sole discipler of every teenage boy in the troop"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    6,
    'Committee',
    'Treasurer',
    'Stewards troop finances with integrity, clarity, and care.',
    'The Treasurer manages all troop finances: tracks income and expenses, processes Stripe payments, provides monthly financial reports, and maintains accurate records year-round. This is the financial backbone of the troop — every family and every boy benefits from a treasurer who does this well.',
    1,
    true,
    'Proverbs 27:23 — Know well the condition of your flocks.',
    '2–3 hours per month',
    'Troop Committee Chair',
    '["Monthly financial reports delivered to the committee","Dues and event payments processed accurately","Budget stays healthy across the full year","Records are clean and ready for year-end review"]'::jsonb,
    '["Not making unilateral financial decisions","Not responsible for fundraising — that is a separate role"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    7,
    'Committee',
    'Assistant Treasurer',
    'Supports the Treasurer with Stripe payments and recordkeeping.',
    'Assists the Treasurer with day-to-day financial tasks, especially Stripe payment processing, dues tracking, and monthly reconciliation. A great way to learn troop operations and provide reliable backup to the Treasurer.',
    1,
    false,
    'Luke 16:10 — Faithful in little, faithful in much.',
    '1–2 hours per month',
    'Treasurer',
    '["Stripe payments processed accurately and on time","Financial records supported and backed up","Treasurer has a reliable partner throughout the year"]'::jsonb,
    '["Not making financial decisions independently","Not solely responsible for the full budget"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    8,
    'Program Leaders',
    'Woodlands Ranger',
    'Senior program leader for Kindergarten through 5th grade.',
    'The Woodlands Ranger owns the K–5 program. He coordinates curriculum across the Fox, Hawk, and Mountain Lion patrols, mentors Trail Guides, ensures badge work is on track, and brings energy and vision to the youngest Trailmen in the troop. He is the primary adult voice over the Woodlands branch.',
    1,
    true,
    'Deuteronomy 6:7 — You shall teach them diligently to your children.',
    '3–5 hrs/week',
    'Troopmaster',
    '["Woodlands Trail Guides are supported, equipped, and not going it alone","Curriculum is sequenced across the year — no random Thursday nights","Boys are advancing and being challenged appropriately for their age","Parents of Woodlands boys feel the troop is organized and intentional"]'::jsonb,
    '["Not running every patrol himself — he leads and equips Trail Guides","Not responsible for the full troop program (that is the Troopmaster)"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    9,
    'Program Leaders',
    'Assistant Woodlands Ranger',
    'Right-hand support for the Woodlands branch.',
    'Supports the Woodlands Ranger in coordinating the K–5 program. Covers when the Ranger is absent, assists with Trail Guide mentoring, and takes ownership of specific curriculum or event logistics as assigned. A great role for a dad who wants to grow toward senior leadership.',
    1,
    true,
    'Proverbs 27:17 — As iron sharpens iron, so one man sharpens another.',
    '2–4 hrs/week',
    'Woodlands Ranger',
    '["Woodlands runs smoothly when the Ranger is out","Trail Guides have two experienced adults to go to with questions","He is actively learning the Ranger role with eyes on succession"]'::jsonb,
    '["A backup who only shows up when asked","Someone waiting for the Ranger to assign tasks every week"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    10,
    'Program Leaders',
    'Navigator Trail Master',
    'Senior program leader for middle school Navigators.',
    'The Navigator Trail Master leads the middle school branch. He oversees weekly programming for Navigator-aged boys, mentors youth patrol leaders, drives advancement, and creates the kind of environment where teenage boys want to show up on Thursday nights. This is a high-relational, high-impact role.',
    1,
    true,
    'Proverbs 13:20 — Walk with the wise and become wise.',
    '3–5 hrs/week',
    'Troopmaster',
    '["NAV boys are engaged, advancing, and growing in faith and character","Youth Patrol Leaders are being mentored and stretched","Thursday nights feel purposeful — not just another meeting","Guys in middle school are actually excited to be there"]'::jsonb,
    '["Not doing every lesson himself — he deploys and coaches Trail Guides","Not just the most experienced guy in the room — he is actively developing the next layer of leaders"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    11,
    'Program Leaders',
    'Asst. Navigator Trail Master',
    'Partners with the Trail Master to lead Navigator programming.',
    'Supports the Navigator Trail Master in all aspects of middle school programming. Covers meetings when the Trail Master is absent, builds relationships with individual boys, and owns specific programming or logistics as delegated. Ideal for a dad who loves middle school guys and wants to grow in leadership.',
    1,
    true,
    'Ecclesiastes 4:9 — Two are better than one, because they have a good reward for their toil.',
    '2–4 hrs/week',
    'Navigator Trail Master',
    '["NAV programming continues without disruption when the Trail Master is out","Boys in the NAV branch know and trust him — he is a real presence, not a backup","He is clearly growing into the Trail Master role"]'::jsonb,
    '["A placeholder — he is in the room, in the relationships, and in the program every week"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    12,
    'Program Leaders',
    'Adventurer Advisor',
    'Senior program leader for high school Adventurers.',
    'The Adventurer Advisor leads the high school branch. He works with older teenage boys who are close to launching into manhood — his job is to make that launch count. He oversees programming, mentors youth leaders, drives challenge and discipleship, and creates the capstone experience of a young man''s Trail Life journey.',
    1,
    true,
    '1 Timothy 4:12 — Set the believers an example in speech, in conduct, in love, in faith, in purity.',
    '3–5 hrs/week',
    'Troopmaster',
    '["Adventurer boys are being genuinely discipled — not just programmed","Older boys are given real responsibility and trusted with it","Guys finishing their Trail Life career do so with a clear sense of identity and purpose","The NAV/ADS division feels like one unified culture of older men and boys"]'::jsonb,
    '["Just a program manager — this role is fundamentally relational","Doing the work for the boys — he gives them the weight and watches them carry it"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    13,
    'Program Leaders',
    'Asst. Adventurer Advisor',
    'Supports the Advisor and builds deep relationships with high school guys.',
    'Partners with the Adventurer Advisor to lead the high school program. Takes ownership of specific relationships, program elements, or campout logistics as assigned. A tremendous opportunity for a man who wants to pour into older teenage boys at a pivotal moment in their lives.',
    1,
    true,
    'Titus 2:6-7 — Urge the younger men to be self-controlled. Show yourself in all respects to be a model of good works.',
    '2–4 hrs/week',
    'Adventurer Advisor',
    '["High school guys know him by name and trust him enough to talk","He covers for the Advisor without the program losing momentum","He is growing in his ability to disciple older teenage men"]'::jsonb,
    '["Someone who just shows up — this role demands investment in individual boys"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    14,
    'Trail Guides',
    'Trail Guide — Woodlands Fox',
    'Frontline mentor for Fox Patrol boys — the role that changes a life.',
    'Trail Guides are the frontline mentors for Trailmen. Fox Patrol needs 3 guides — a Primary and two Secondaries — to run weekly badge work, walk boys through advancement, and build the kind of relationships that shape character for a lifetime.',
    3,
    true,
    'Proverbs 22:6 — Train up a child in the way he should go.',
    '5–10 hours per month',
    'Woodlands Ranger',
    '["Boys advance consistently and know someone is in their corner","Patrol runs with purpose and brotherhood","Deep trust built between guide and each boy","Boys grow in faith, outdoor skills, and leadership"]'::jsonb,
    '["Not doing advancement for the boys — guiding them through it","Not running meetings alone — you have a team"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    15,
    'Trail Guides',
    'Trail Guide — Woodlands Hawk',
    'Frontline mentor for Hawk Patrol boys.',
    'Hawk Patrol needs 3 Trail Guides to walk alongside boys week after week. This is the most direct investment you can make — showing up Thursday nights, leading badge work, and building relationships that boys will remember decades from now.',
    3,
    true,
    'Proverbs 22:6 — Train up a child in the way he should go.',
    '5–10 hours per month',
    'Woodlands Ranger',
    '["Hawk boys advance consistently and know their guide by name","Weekly badge work is prepared and engaging","Boys feel challenged, known, and encouraged","Patrol has strong culture and accountability"]'::jsonb,
    '["Not solely responsible for all badge content — Trail Life provides curriculum","Not operating alone — you have co-guides"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    16,
    'Trail Guides',
    'Trail Guide — Woodlands Mountain Lion',
    'Frontline mentor for Mountain Lion Patrol boys.',
    'Mountain Lion Patrol needs 3 guides committed to the weekly work of mentoring boys through badge advancement and character formation. The most impactful role in the troop — right in the room with the boys every Thursday.',
    3,
    true,
    'Proverbs 22:6 — Train up a child in the way he should go.',
    '5–10 hours per month',
    'Woodlands Ranger',
    '["Mountain Lion boys are advancing and engaged","Guides know each boy''s progress and next steps","Boys experience real mentorship, not just programming","Patrol thrives even when one guide is absent"]'::jsonb,
    '["Not doing the work for the boys","Not expected to be perfect — just present and consistent"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    17,
    'Trail Guides',
    'Trail Guide — Navigators',
    'Mentor for middle school Navigators — big investment, big return.',
    'Navigator guides walk with middle school boys through a critical window of development. Three guides share the load — leading weekly programming, driving advancement, and building the kind of trust that gives teenage boys a safe place to grow into men.',
    3,
    true,
    'Proverbs 27:17 — As iron sharpens iron, so one man sharpens another.',
    '5–10 hours per month',
    'Navigator Trail Master',
    '["Navigator boys are advancing and showing up consistently","Guides know their boys'' lives beyond Thursday nights","Boys are being equipped for leadership roles","Middle school years are marked by meaningful growth"]'::jsonb,
    '["Not a babysitter or enforcer","Not running everything alone — three guides share the work"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    18,
    'Trail Guides',
    'Trail Guide — Adventurers',
    'Mentor for high school Adventurers — invest in the next generation of men.',
    'Adventurer guides invest in high school boys during the final stretch before adulthood. Three guides work alongside the Adventurer Advisor to run a program that challenges young men, builds real outdoor skills, and points them toward Christ-centered manhood.',
    3,
    true,
    '1 Timothy 4:12 — Let no one despise you for your youth.',
    '5–10 hours per month',
    'Adventurer Advisor',
    '["Adventurers are engaged, challenged, and taking ownership","Boys move toward Freedom Award and meaningful milestone events","Guides have genuine mentoring relationships with their guys","High school years are marked by adventure and character formation"]'::jsonb,
    '["Not a peer — you are a guide and mentor","Not expected to have all the answers — just to show up faithfully"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    19,
    'Support',
    'Outdoor Activities Chair',
    'Coordinates campouts, hikes, and all outdoor adventures.',
    'The Outdoor Activities Chair ensures troop outdoor events are safe, fun, and aligned with Trail Life values. This role oversees site research, reservations, and the planning process — supervising grub masters and supporting youth leaders so they can focus on the boys.',
    1,
    true,
    'Genesis 1:31 — God saw all he had made, and it was very good.',
    '4–6 hours per month',
    'Troopmaster',
    '["Full outdoor calendar planned 4–6 weeks ahead","Events well-attended and run smoothly","Boys experience challenge, beauty, and brotherhood outdoors"]'::jsonb,
    '["Not running every event alone","Not the outdoor skills instructor — that is the Trail Guide"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    20,
    'Support',
    'Fundraising Chair',
    'Leads troop fundraising so no boy is ever left out.',
    'Leads troop fundraising by coordinating campaigns, community partnerships, and family involvement. Works with the Treasurer and Points Manager to ensure resources are available for every boy to participate — regardless of financial situation. Leads a small team including family volunteers.',
    1,
    true,
    '2 Corinthians 9:7 — God loves a cheerful giver.',
    '4–6 hours per month',
    'Troop Committee Chair',
    '["Annual fundraising goals met","Parents and youth engaged and motivated","Scholarship fund supported throughout the year","No boy misses out due to cost"]'::jsonb,
    '["Not funding the troop personally","Not operating alone — builds and leads a small team"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    21,
    'Committee',
    'Treasurer',
    'Stewards troop finances with integrity, clarity, and care.',
    'The Treasurer manages all troop finances: tracks income and expenses, processes Stripe payments, provides monthly financial reports, and maintains accurate records year-round. This is the financial backbone of the troop — every family and every boy benefits from a treasurer who does this well.',
    1,
    true,
    'Proverbs 27:23 — Know well the condition of your flocks.',
    '2–3 hours per month',
    'Troop Committee Chair',
    '["Monthly financial reports delivered to the committee","Dues and event payments processed accurately","Budget stays healthy across the full year","Records are clean and ready for year-end review"]'::jsonb,
    '["Not making unilateral financial decisions","Not responsible for fundraising — that is a separate role"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    22,
    'Support',
    'Communications Manager',
    'Keeps families informed through clear, consistent updates.',
    'The Communications Manager keeps parents, youth, and leaders consistently informed about troop activities and vision. This person is the information hub — ensuring announcements, schedules, and updates reach families clearly across email, Slack, and group text.',
    1,
    false,
    'Colossians 4:6 — Let your speech always be gracious.',
    '2–3 hours per month',
    'Troop Committee Chair or Troopmaster',
    '["Weekly or bi-weekly updates go out on time","Parents know where to find troop information","Major events communicated at least 2 weeks in advance","Families feel connected and in the loop"]'::jsonb,
    '["Not responsible for creating all event content","Not expected to answer every question instantly","Not in charge of setting the troop calendar"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    23,
    'Support',
    'Calendar Manager',
    'Maintains the master troop calendar so families can plan ahead.',
    'The Calendar Manager maintains the master troop calendar, ensuring all events are scheduled, communicated, and conflict-free well in advance. Works closely with the Communications Manager and Program Leaders to help every family stay ahead of the schedule.',
    1,
    false,
    '1 Corinthians 14:40 — All things done decently and in order.',
    '2–3 hours per month',
    'Troopmaster',
    '["All events entered promptly and accurately","No scheduling conflicts across the year","Parents and youth rely on the calendar with confidence"]'::jsonb,
    '["Not responsible for planning every event","Not responsible for last-minute reminders"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    24,
    'Support',
    'Onboarding Coordinator',
    'Welcomes new families into troop life with warmth and clarity.',
    'The Onboarding Coordinator ensures every new family feels valued and quickly connected. They explain troop structure, help parents find where to serve, answer key questions, and ensure the first few weeks for a new family are smooth and encouraging.',
    1,
    false,
    'Romans 15:7 — Welcome one another as Christ welcomed you.',
    '2–4 hours per month',
    'Troop Committee Chair',
    '["New families welcomed within their first week","Parents oriented to troop structure and Slack","Youth matched with patrols smoothly","New families feel they belong here"]'::jsonb,
    '["Not responsible for all paperwork","Not the sole point of contact for every question"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    25,
    'Support',
    'Snack Coordinator',
    'Organizes the weekly snack rotation to support fellowship.',
    'Ensures every troop meeting has snacks coordinated fairly among families by maintaining a simple rotation schedule and sending friendly reminders. Small role, real impact on the warmth of Thursday nights.',
    1,
    false,
    'Hebrews 13:2 — Do not neglect to show hospitality.',
    '1 hour per month',
    'Troopmaster or Committee Chair',
    '["Snack schedule shared at the start of each semester","Families reminded a week in advance","Snacks provided consistently at every meeting"]'::jsonb,
    '["Not expected to provide all snacks personally","Not responsible for cleanup"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    26,
    'Support',
    'Worship Leader',
    'Leads the troop in worship to keep Christ central.',
    'Ensures spiritual focus in troop meetings through songs, devotions, and Scripture. Coordinates youth participation where possible and partners with the Navigator Chaplain''s Aide. Keeps Christ at the center of every Thursday night.',
    1,
    false,
    'Psalm 100:2 — Serve the Lord with gladness!',
    '2–3 hours per month',
    'Troopmaster or Chaplain',
    '["Regular spiritual content woven into meetings","Youth engaged and participating in worship","Families encouraged in their faith week to week"]'::jsonb,
    '["Not expected to preach full sermons","Not solely responsible for the troop''s spiritual depth"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    27,
    'Support',
    'Community Service Chair',
    'Coordinates service projects that let boys put faith into action.',
    'Identifies, organizes, and oversees troop service projects in partnership with local organizations. Ensures that Trailmen are actively serving in the community throughout the year — not just camping and adventuring, but giving back.',
    1,
    false,
    'Matthew 5:16 — Let your light shine before others.',
    '3–5 hours per project',
    'Troop Committee Chair',
    '["Troop completes multiple meaningful service projects per year","Youth actively engaged in planning and serving","Community impact is visible and the troop is known for it"]'::jsonb,
    '["Not personally responsible for all volunteer hours","Not operating alone — recruits family help for each project"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    28,
    'Support',
    'Equipment Coordinator',
    'Manages troop gear so every adventure is ready to go.',
    'Responsible for all troop equipment — organizing, maintaining, and tracking gear for safe use at campouts and meetings. Partners with the Navigator Quartermaster to keep inventory current and damaged gear replaced promptly.',
    1,
    false,
    'Ecclesiastes 10:10 — Skill and preparation bring success.',
    '2–3 hours per month',
    'Troopmaster',
    '["All equipment available and in working order for every event","Inventory tracked and current","Damaged or missing gear flagged and replaced quickly"]'::jsonb,
    '["Not storing all gear at home alone","Not funding equipment purchases personally"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    29,
    'Support',
    'Health & Safety Chair',
    'Ensures the troop has solid safety protocols at every event.',
    'Develops troop safety procedures, ensures first aid kits are stocked and present at every event, and coordinates the Medical Safety Officer role for campouts. Partners with the Medical Forms Coordinator to ensure no boy attends an event without current forms on file.',
    1,
    false,
    'Psalm 121:7 — The Lord will keep you from all harm.',
    '2–3 hours per month',
    'Troopmaster',
    '["Safety kits stocked and present at every event","Safety protocols known and followed by all leaders","Medical needs documented and accessible in the field"]'::jsonb,
    '["Not solely responsible for all emergency response","Not a replacement for professional medical personnel"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    30,
    'Support',
    'Historian',
    'Captures the troop''s story through photos, video, and memories.',
    'Keeps record of troop events through photos, videos, and written accounts. Builds a growing archive of the troop''s journey that families and boys will look back on for years. Partners with the PR & Social Media Chair for content.',
    1,
    false,
    'Psalm 77:11 — I will remember the deeds of the Lord.',
    '2–3 hours per month',
    'Troopmaster',
    '["Events documented consistently throughout the year","Photo archive organized and accessible to families","Year-end memories captured and celebrated"]'::jsonb,
    '["Not responsible for publicity alone","Not required to be at every single event"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    31,
    'Support',
    'Medical Forms Coordinator',
    'Manages medical and consent forms for every boy at every event.',
    'Collects and organizes medical forms for each Trailman to ensure the troop is ready for any situation at every event. Keeps records current, notifies families of missing forms, and ensures leaders have access in the field.',
    1,
    false,
    'Philippians 2:4 — Look not only to your own interests, but to the interests of others.',
    '2–3 hours per quarter',
    'Health & Safety Chair',
    '["All medical forms collected before each campout","Forms organized and accessible to event leaders","Families notified promptly of expired or missing forms"]'::jsonb,
    '["Not giving medical treatment","Not solely responsible for emergency response"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    32,
    'Support',
    'Parent Advancement Coordinator',
    'Supports the advancement journey alongside Trail Guides.',
    'Helps track, encourage, and support Trailmen in their advancement work. Partners with Trail Guides to ensure no boy falls behind, and prepares recognition for Courts of Honor. A great role for a parent who wants to be involved in the boys'' progress.',
    1,
    false,
    '2 Timothy 2:2 — Entrust to faithful men who will teach others also.',
    '2–3 hours per month',
    'Troopmaster',
    '["Youth stay on track with advancement goals","Courts of Honor are well-prepared and meaningful","Parents are informed of their son''s progress"]'::jsonb,
    '["Not doing advancement work for the youth","Not making unilateral advancement decisions"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    33,
    'Support',
    'PR & Social Media Chair',
    'Builds the troop''s public presence and tells our story well.',
    'Manages troop social media, posts updates, and promotes events in the community. Helps recruit new families by telling the troop''s story compellingly. Partners with the Historian for photos and content to post.',
    1,
    false,
    'Matthew 5:14 — A city on a hill cannot be hidden.',
    '2–4 hours per month',
    'Troop Committee Chair',
    '["Regular posts celebrating troop life and adventure","Positive troop reputation built in the broader community","New families discover the troop through social channels"]'::jsonb,
    '["Not responsible for all photos or content","Not the sole spokesperson for the troop"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    34,
    'Support',
    'Book Manager',
    'Keeps handbooks, curricula, and advancement materials stocked.',
    'Responsible for tracking handbooks, guides, and troop-related resources. Ensures new families can quickly access materials and advancement resources are always stocked. Works closely with the Onboarding and Advancement teams.',
    1,
    false,
    'Proverbs 3:3 — Write them on the tablet of your heart.',
    '1–2 hours per month',
    'Parent Advancement Coordinator',
    '["Troop handbooks current and available for every boy","Families have the correct advancement resources","Inventory tracked and updated regularly"]'::jsonb,
    '["Not teaching or running advancement directly","Not deciding curriculum without troop leadership input"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    35,
    'Support',
    'T-Shirt Manager',
    'Handles troop apparel orders for unity and identity.',
    'Organizes the ordering and distribution of troop t-shirts and other apparel. Ensures shirts are available for new families and that special runs are done for campouts. Coordinates with the Treasurer on payments and the PR Chair for branding consistency.',
    1,
    false,
    'Colossians 3:17 — Do everything in the name of the Lord Jesus.',
    '2–3 hours per order cycle',
    'Troop Committee Chair',
    '["T-shirt orders available twice per year or as needed","Families receive shirts promptly after ordering","Apparel reflects troop unity and identity clearly"]'::jsonb,
    '["Not designing shirts independently without leader input","Not financially responsible for orders"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    36,
    'Support',
    'Camping Coordinator',
    'Organizes campout logistics so leaders can focus on the boys.',
    'Oversees planning and logistics for troop campouts — site reservations, registration deadlines, equipment coordination, and food planning. Ensures youth leaders and Trail Guides have everything they need to focus on discipling boys rather than managing logistics.',
    1,
    false,
    'Proverbs 16:3 — Commit your work to the Lord, and your plans will be established.',
    '4–6 hours per campout',
    'Outdoor Activities Chair',
    '["Campouts planned and communicated 4–6 weeks in advance","Logistics run smoothly from arrival to departure","Families know exactly what to bring and what to expect"]'::jsonb,
    '["Not leading campout activities — that is the Trail Guides'' role","Not personally responsible for providing gear or food"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    37,
    'Support',
    'Fitness Challenge Coordinator',
    'Builds a culture of physical readiness and healthy competition.',
    'Designs and runs periodic fitness challenges for Trailmen across all branches — Woodlands through Adventurers. Tracks scores, celebrates progress, and connects physical discipline to the biblical principle of stewarding the bodies God gave us. Coordinates with Trail Guides to integrate challenges into Thursday nights and campout programming.',
    1,
    false,
    '1 Corinthians 9:27 — I discipline my body and keep it under control.',
    '2–4 hours/month',
    'Troop Committee Chair',
    '["At least one troop-wide fitness challenge per semester","All branches engaged with age-appropriate physical goals","Boys and leaders see connection between physical discipline and godly character","Results tracked and celebrated at Courts of Honor"]'::jsonb,
    '["Not running physical education classes or acting as a personal trainer","Not responsible for medical screening — defers to Safety Officer and parent judgment"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    38,
    'Support',
    'Scripture Memory Coordinator',
    'Keeps God''s Word in the hearts of Trailmen all year long.',
    'Selects, introduces, and tracks a troop-wide Scripture memory plan across the 2026-2027 season. Coordinates recitation moments at Thursday meetings, Courts of Honor, and campouts. Works with the Chaplain and Trail Guides to reinforce verses in patrol settings. Goal: every Trailman leaves the year with God''s Word written on his heart.',
    1,
    false,
    'Psalm 119:11 — I have stored up your word in my heart, that I might not sin against you.',
    '1–2 hours/month',
    'Chaplain',
    '["A fresh memory verse introduced each month or theme unit","Boys can recite key verses at Courts of Honor","Recitation integrated naturally into meetings — not as a drill, but as worship","Patrol leaders empowered to carry the verse in their patrol"]'::jsonb,
    '["Not policing or grading memory — encouraging and celebrating progress","Not creating a second curriculum — works within the existing program rhythm"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    39,
    'Support',
    'Technology Chair / Webmaster',
    'Keeps the troop''s digital presence working and accessible.',
    'Manages the troop website (troop9871.org), handles tech setup for meetings and events (slides, display screens, audio), maintains the troop email platform, and serves as the go-to resource when technology isn''t working. Works closely with the Communications Chair on digital distribution.',
    1,
    false,
    'Colossians 3:23 — Whatever you do, work heartily, as for the Lord.',
    '2–4 hrs/month',
    'Troop Committee Chair',
    '["Troop website is current, accurate, and easy for families to navigate","Meeting AV and display needs are set up and working before the first Trailman arrives","Troop email platform is configured and running reliably","Tech problems get solved quickly without derailing leadership bandwidth"]'::jsonb,
    '["Not a full IT department — focuses on the troop''s specific tools and platforms","Not responsible for families'' personal devices or home internet issues"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    adults_id,
    40,
    'Support',
    'Registration Desk Lead',
    'First face families see. Sets the tone every Thursday.',
    'Runs the check-in table at Thursday meetings — greeting families, recording attendance, handling sign-up sheets, collecting forms, and directing new families to the right place. Partners with the Registrar to ensure attendance records are accurate and that no family slips through the cracks on their first night.',
    1,
    false,
    'Romans 15:7 — Welcome one another as Christ has welcomed you.',
    '1–2 hrs/week (Thursday evenings)',
    'Registrar / Committee Chair',
    '["Every boy is checked in and attendance logged by 6:45 PM","New families are warmly welcomed and pointed to the right patrol within minutes of arrival","Sign-in process is smooth — no line, no confusion","He knows the regulars by name and notices when someone is missing"]'::jsonb,
    '["A passive sign-in station — this role is relational, not just administrative","Responsible for Registrar-level data management (he hands off records, he does not own the system)"]'::jsonb,
    '[]'::jsonb
    );


  -- Youth event ---------------------------------------------
  insert into public.events (slug, title, subtitle, season, is_published, theme)
  values (
    'leadership-youth-2026-27',
    'Youth Leadership Roles · 2026–2027',
    'Lead your patrol. Trail Life MN-9871 leadership signup for boys.',
    '2026-2027',
    true,
    'trail-life-gold'
  )
  on conflict (slug) do update set
    title       = excluded.title,
    subtitle    = excluded.subtitle,
    season      = excluded.season,
    is_published= excluded.is_published,
    theme       = excluded.theme;

  select id into youth_id from public.events where slug = 'leadership-youth-2026-27';
  delete from public.slots where event_id = youth_id;

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    youth_id,
    0,
    'Leadership',
    'Patrol Leader',
    'Lead your patrol. Set the tone every Thursday.',
    'The Patrol Leader is the senior youth voice in his patrol. He opens meetings, assigns tasks, keeps order, and leads his guys through the weekly agenda. He is the first call when something goes sideways and the first to model servant leadership. This is the highest youth leadership role in the troop.',
    2,
    true,
    '"Let no one despise you for your youth, but set the believers an example." — 1 Timothy 4:12',
    '~3 hrs/week (meetings + prep)',
    'Navigator Trail Master',
    '["His patrol runs smoothly even when adults step back","Every guy in the patrol knows what is happening and what is expected","He knows each boy by name and is intentional about including everyone","He shows up early, stays late, and leaves the space better than he found it"]'::jsonb,
    '["A boss who barks orders — he leads by example","The adult Trail Guide (he defers to adult leaders on safety and discipline)","Optional — he is at every meeting unless sick or pre-approved absent"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    youth_id,
    1,
    'Leadership',
    'Junior Patrol Leader',
    'Second in command. Learning to lead from the inside.',
    'The Jr Patrol Leader is the Patrol Leader''s right hand. He runs the patrol when the PL is absent, assists with logistics, and is actively growing into the top role. This is the proving ground for future Patrol Leaders.',
    2,
    true,
    '"Whoever would be great among you must be your servant." — Matthew 20:26',
    '~2 hrs/week (meetings + prep)',
    'Patrol Leader',
    '["Covers for the Patrol Leader without the meeting falling apart","Knows every guy''s advancement status and nudges them toward next steps","Completes assigned tasks without being reminded","Is clearly growing in leadership maturity by May"]'::jsonb,
    '["A backup who does nothing until the PL is gone","Someone who waits to be told what to do every week","A title with no substance"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    youth_id,
    2,
    'Crew',
    'Navigator Scribe',
    'The keeper of the record. Words matter.',
    'The Scribe takes notes at patrol and troop meetings, records attendance, tracks decisions made, and keeps the patrol''s written record clean and current. He may also draft communications to patrol members between meetings.',
    1,
    false,
    '"Write the vision; make it plain." — Habakkuk 2:2',
    '1-2 hrs/week',
    'Patrol Leader',
    '["Every meeting has a short written record within 24 hours","Attendance is accurate and handed off to the Registrar each week","Communication between meetings is clear and timely","His records could tell the story of the troop year end to end"]'::jsonb,
    '["A full-time secretary (notes should be brief and useful, not exhaustive)","The person who sends mass emails on behalf of the whole troop (that is Communications Chair)"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    youth_id,
    3,
    'Crew',
    'Navigator Quartermaster',
    'Gear steward. Knows where everything is and keeps it that way.',
    'The Quartermaster is responsible for tracking, organizing, and distributing patrol gear. He checks gear in and out for campouts, flags damaged or missing items to adult leaders, and keeps the patrol kit ready to go at all times.',
    1,
    false,
    '"Each of you should use whatever gift you have received to serve others." — 1 Peter 4:10',
    '1-2 hrs/week',
    'Patrol Leader / Equipment Master',
    '["Patrol gear is clean, organized, and accounted for after every campout","Damaged or missing gear is reported within 48 hours","Every patrol member knows the check-out process","No gear is left behind at an event"]'::jsonb,
    '["The person who buys new gear (that is the adult Equipment Master)","Responsible for adult gear or the trailer (that belongs to the Troop Quartermaster)"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    youth_id,
    4,
    'Crew',
    'Chaplain''s Aide',
    'The spiritual heartbeat of the patrol. Prayer and presence.',
    'The Chaplain''s Aide leads patrol prayer, assists with devotional moments, and is attentive to the spiritual and emotional health of his patrol brothers. He works alongside the adult Chaplain and is the go-between for guys who need prayer or encouragement. Two spots — one for Navigators, one for Adventurers.',
    2,
    false,
    '"Pray without ceasing." — 1 Thessalonians 5:17',
    '1-2 hrs/week',
    'Chaplain / Patrol Leader',
    '["Every meeting opens and closes with prayer he leads or coordinates","He notices when a guy is struggling and quietly checks in","Devotional moments are prepared and meaningful, not rushed","He is growing in his own faith and it shows"]'::jsonb,
    '["Required to be a theologian — just a guy who takes prayer seriously","The Chaplain himself (that is an adult role) — he assists and facilitates"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    youth_id,
    5,
    'Leadership',
    'Color Guard Commander',
    'Lead the Color Guard. Own the ceremony.',
    'The Color Guard Commander leads and trains the Color Guard team. He calls commands, sets the standard for precision and reverence, and ensures the team is ready for every flag ceremony. He coordinates with the Troopmaster for special events and courts of honor. Two Commander spots — one primary, one secondary.',
    2,
    true,
    '"Whatever you do, do it heartily, as to the Lord and not to men." — Colossians 3:23',
    '~1.5 hrs/week (meetings + pre-event practice)',
    'Patrol Leader / Troopmaster',
    '["Color Guard is trained, sharp, and ready before every meeting","Commands are called clearly and the team moves as one","He holds the team to the standard without being harsh","Every ceremony honors God, country, and the troop well"]'::jsonb,
    '["A figurehead — he trains and leads, not just stands in front","Responsible for deciding ceremony format unilaterally (defers to Troopmaster)"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    youth_id,
    6,
    'Crew',
    'Color Guard',
    'Honor and carry the flag with dignity.',
    'Color Guard members carry, present, and retire the American flag and Troop flag at troop meetings, courts of honor, and special events. This is a high-visibility role that demands precision, respect, and showing up prepared. 10 spots total.',
    10,
    false,
    '"Stand firm in one spirit, with one mind striving side by side." — Philippians 1:27',
    '~1 hr/week (meetings + events)',
    'Color Guard Commander / Patrol Leader',
    '["Every flag ceremony is executed cleanly and with reverence","Color Guard members arrive early enough to practice before the meeting","Uniforms are complete and pressed for ceremonies","The flag is never allowed to touch the ground"]'::jsonb,
    '["A ceremonial-only role — Color Guard members are expected to serve in other patrol roles too","Optional when you feel like it — flag ceremonies require the full team"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    youth_id,
    7,
    'Crew',
    'Facility Manager',
    'Set it up. Break it down. Leave it better.',
    'Facility Managers handle room setup before meetings and teardown after. This includes chairs, tables, equipment staging, and making sure the space is clean before leaving. Three spots per patrol (Navigator and Adventurer patrols each need 3).',
    6,
    false,
    '"Whatever you do, work heartily, as for the Lord." — Colossians 3:23',
    '~1 hr/week',
    'Patrol Leader',
    '["The room is ready before the first guy arrives","Cleanup is done by 9:30 PM every week without being asked","Chairs, tables, and gear are stored correctly and the building is left with respect","He takes ownership of the space like it belongs to him"]'::jsonb,
    '["The janitor (this is about stewardship, not punishment)","A rotating chore for whoever shows up last"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    youth_id,
    8,
    'Crew',
    'Youth Snack Coordinator',
    'Feed the troops. Hungry guys are grumpy guys.',
    'The Youth Snack Coordinator works with the adult Snack Coordinator to organize the weekly snack rotation, collect sign-ups from families, and make sure snack is ready and available at break time. He communicates with families who signed up and follows up if anything falls through.',
    2,
    false,
    '"Share with the Lord''s people who are in need." — Romans 12:13',
    '30 min/week',
    'Patrol Leader / Snack Coordinator (adult)',
    '["Snack is ready at break every week without fail","Families who signed up know what to bring and when","He follows up with the adult Snack Coordinator if there is a gap","Dietary needs for guys in the patrol are known and communicated"]'::jsonb,
    '["The person who provides all the snacks himself (he organizes, not funds)","Responsible for adult snacks (that is the adult Snack Coordinator)"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    youth_id,
    9,
    'Crew',
    'NAV/ADD Calendar Manager',
    'Keeps the Navigator and Adventurer schedule clear and current.',
    'The NAV/ADD Calendar Manager tracks and communicates upcoming events, meetings, campouts, and deadlines specific to the Navigator and Adventurer branches. He keeps a shared calendar current, sends reminders to patrol members and families, and coordinates with adult Communications Chair on troop-wide announcements.',
    1,
    false,
    '"For everything there is a season, and a time for every matter under heaven." — Ecclesiastes 3:1',
    '1-2 hrs/month',
    'Patrol Leader / Communications Chair (adult)',
    '["Every NAV/ADD event is on the calendar at least 2 weeks in advance","Guys in the patrol know what is coming up and what they need to bring","No one misses a campout because they forgot to sign up","He is proactive — not waiting to be asked to update the calendar"]'::jsonb,
    '["Responsible for the full troop calendar (that is the adult Communications Chair)","Required to design graphics or manage social media"]'::jsonb,
    '[]'::jsonb
    );

  insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
    ) values (
    youth_id,
    10,
    'Crew',
    'NAV/ADD Advancement Manager',
    'Keeps every Trailman moving forward on his advancement journey.',
    'The NAV/ADD Advancement Manager tracks where every Navigator and Adventurer stands on his advancement goals, flags guys who are falling behind, and coordinates with Trail Guides and the adult Advancement Chair to keep everyone moving. He knows who needs what and helps make sure no Trailman gets stuck. Two spots — one Navigator, one Adventurer.',
    2,
    false,
    '"Press on toward the goal for the prize of the upward call of God in Christ Jesus." — Philippians 3:14',
    '1-2 hrs/week',
    'Patrol Leader / Advancement Chair (adult)',
    '["He knows the advancement status of every guy in his branch","Boys who are stuck get connected to the right resource or leader within a week","Courts of Honor are well-prepared because advancement records are clean","He communicates regularly with the adult Advancement Chair"]'::jsonb,
    '["The person who completes advancement for anyone else — he tracks and encourages, not does it for them","Responsible for Woodlands advancement (that is a separate system)"]'::jsonb,
    '[]'::jsonb
    );

end $$;

commit;