#!/usr/bin/env node
// ============================================================
// build-seed.mjs
// Extracts the ROLES array literal from each of the legacy
// static-site HTML files and emits a SQL seed file for Supabase
// that creates two events (adults, youth) plus all of their slots.
//
// Run: node scripts/build-seed.mjs
// Output: app/supabase/seed.sql
// ============================================================

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..", "..");
const ADULTS_HTML = resolve(
  REPO_ROOT,
  "signup-static",
  "2026-2027-Volunteer-Signup-Adults.html",
);
const YOUTH_HTML = resolve(
  REPO_ROOT,
  "signup-static",
  "2026-2027-Volunteer-Signup-Youth.html",
);
const OUTPUT = resolve(__dirname, "..", "supabase", "seed.sql");

// Section-ID hints from the adult HTML — used to derive group_label.
const COMMITTEE_IDS = new Set([
  "troopmaster",
  "asst-troopmaster",
  "committee-chair",
  "chaplain",
  "chaplain-asst-woodlands",
  "chaplain-asst-navads",
  "treasurer",
  "assistant-treasurer",
]);
const PROGRAM_LEADER_IDS = new Set([
  "woodlands-ranger",
  "asst-woodlands-ranger",
  "navigator-trail-master",
  "asst-navigator-trail-master",
  "adventurer-advisor",
  "asst-adventurer-advisor",
]);
const TRAIL_GUIDE_IDS = new Set([
  "trail-guide-fox",
  "trail-guide-hawk",
  "trail-guide-mountain-lion",
  "trail-guide-navigator",
  "trail-guide-adventurer",
]);

function adultGroupLabel(id) {
  if (COMMITTEE_IDS.has(id)) return "Committee";
  if (PROGRAM_LEADER_IDS.has(id)) return "Program Leaders";
  if (TRAIL_GUIDE_IDS.has(id)) return "Trail Guides";
  return "Support";
}

// Parse the ROLES = [...]; literal out of a given HTML file by locating
// the matching brackets and evaluating the slice as JavaScript. The HTML
// files are first-party so eval is safe here.
function extractRolesArray(source) {
  const startMatch = source.match(/const\s+ROLES\s*=\s*\[/);
  if (!startMatch) throw new Error("ROLES literal not found");
  const startIdx = startMatch.index + startMatch[0].length - 1; // points at `[`

  let depth = 0;
  let inString = false;
  let stringChar = "";
  let prev = "";
  let endIdx = -1;

  for (let i = startIdx; i < source.length; i++) {
    const ch = source[i];
    if (inString) {
      if (ch === stringChar && prev !== "\\") inString = false;
    } else {
      if (ch === "'" || ch === '"' || ch === "`") {
        inString = true;
        stringChar = ch;
      } else if (ch === "[") {
        depth += 1;
      } else if (ch === "]") {
        depth -= 1;
        if (depth === 0) {
          endIdx = i + 1;
          break;
        }
      }
    }
    prev = ch;
  }

  if (endIdx === -1) throw new Error("Unclosed ROLES array");
  const literal = source.slice(startIdx, endIdx);
  // eslint-disable-next-line no-new-func
  return new Function(`return ${literal};`)();
}

function sqlText(v) {
  if (v === undefined || v === null) return "NULL";
  return `'${String(v).replace(/'/g, "''")}'`;
}

function sqlJson(arr) {
  const cleaned = (arr ?? []).map((x) => String(x));
  return `'${JSON.stringify(cleaned).replace(/'/g, "''")}'::jsonb`;
}

function buildSlotInsert(eventVar, role, sortOrder, group) {
  return `insert into public.slots (
    event_id, sort_order, group_label, title, subtitle, description,
    spots, leadership, scripture, time_commitment, reports_to,
    success_bullets, not_this_bullets, prefilled_names
  ) values (
    ${eventVar},
    ${sortOrder},
    ${sqlText(group)},
    ${sqlText(role.name)},
    ${sqlText(role.subtitle ?? null)},
    ${sqlText(role.desc ?? null)},
    ${Number(role.spots) || 1},
    ${role.leadership ? "true" : "false"},
    ${sqlText(role.scripture ?? null)},
    ${sqlText(role.time ?? null)},
    ${sqlText(role.reportsTo ?? null)},
    ${sqlJson(role.success)},
    ${sqlJson(role.notThis)},
    ${sqlJson(role.prefilled ? [role.prefilled] : [])}
  );`;
}

async function main() {
  const adultsSrc = await readFile(ADULTS_HTML, "utf8");
  const youthSrc = await readFile(YOUTH_HTML, "utf8");

  const adultRoles = extractRolesArray(adultsSrc);
  const youthRoles = extractRolesArray(youthSrc);

  const lines = [];
  lines.push(
    "-- ============================================================",
    "-- Seed: 2026-2027 Trail Life MN-9871 Leadership signups",
    "--",
    "-- Generated by app/scripts/build-seed.mjs from the legacy",
    "-- static HTML pages under signup-static/. Run again to refresh.",
    "-- ",
    "-- Run via Supabase Studio SQL Editor, or:",
    "--   psql \"$DATABASE_URL\" -f app/supabase/seed.sql",
    "-- ============================================================",
    "",
    "begin;",
    "",
    "-- Adults event ---------------------------------------------",
    "insert into public.events (slug, title, subtitle, season, is_published, theme)",
    "values (",
    "  'leadership-adults-2026-27',",
    "  'Adult Volunteer Roles · 2026–2027',",
    "  'Step up and serve. Trail Life MN-9871 leadership signup for dads and adults.',",
    "  '2026-2027',",
    "  true,",
    "  'trail-life-green'",
    ")",
    "on conflict (slug) do update set",
    "  title       = excluded.title,",
    "  subtitle    = excluded.subtitle,",
    "  season      = excluded.season,",
    "  is_published= excluded.is_published,",
    "  theme       = excluded.theme;",
    "",
  );

  // Use a DO block so we can pass the event id into slot inserts cleanly,
  // and so re-running the seed is idempotent.
  lines.push("do $$");
  lines.push("declare");
  lines.push("  adults_id uuid;");
  lines.push("  youth_id  uuid;");
  lines.push("begin");
  lines.push(
    "  select id into adults_id from public.events where slug = 'leadership-adults-2026-27';",
  );
  // Fully wipe slots for this event so re-running the seed is idempotent.
  // Signups cascade via FK. Any real signups would be wiped — this is a
  // destructive bootstrap, not a runtime upsert.
  lines.push("  delete from public.slots where event_id = adults_id;");
  lines.push("");

  adultRoles.forEach((role, idx) => {
    const group = adultGroupLabel(role.id);
    lines.push(
      "  " +
        buildSlotInsert("adults_id", role, idx, group).replace(
          /\n\s+/g,
          "\n    ",
        ),
    );
    lines.push("");
  });

  lines.push("");
  lines.push("  -- Youth event ---------------------------------------------");
  lines.push("  insert into public.events (slug, title, subtitle, season, is_published, theme)");
  lines.push("  values (");
  lines.push("    'leadership-youth-2026-27',");
  lines.push("    'Youth Leadership Roles · 2026–2027',");
  lines.push("    'Lead your patrol. Trail Life MN-9871 leadership signup for boys.',");
  lines.push("    '2026-2027',");
  lines.push("    true,");
  lines.push("    'trail-life-gold'");
  lines.push("  )");
  lines.push("  on conflict (slug) do update set");
  lines.push("    title       = excluded.title,");
  lines.push("    subtitle    = excluded.subtitle,");
  lines.push("    season      = excluded.season,");
  lines.push("    is_published= excluded.is_published,");
  lines.push("    theme       = excluded.theme;");
  lines.push("");
  lines.push(
    "  select id into youth_id from public.events where slug = 'leadership-youth-2026-27';",
  );
  lines.push("  delete from public.slots where event_id = youth_id;");
  lines.push("");

  youthRoles.forEach((role, idx) => {
    const group = role.leadership ? "Leadership" : "Crew";
    lines.push(
      "  " +
        buildSlotInsert("youth_id", role, idx, group).replace(
          /\n\s+/g,
          "\n    ",
        ),
    );
    lines.push("");
  });

  lines.push("end $$;");
  lines.push("");
  lines.push("commit;");

  const sql = lines.join("\n");

  await writeFile(OUTPUT, sql, "utf8");
  console.log(
    `Wrote ${OUTPUT} — ${adultRoles.length} adult slots, ${youthRoles.length} youth slots.`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
